### ISSUE TITLE
java-fundamentals-course/0-0-intro/.../Introduction.java 

### ISSUE THREAD

**Issue by orelanc** [bobocode-projects/java-fundamentals-exercises#129]
/**
  ...
  Every exercise is covered with tests. So when you're implementing some class like {@link Introduction}, you should
  also be able to find a corresponding class like {@link IntroductionTest}.
  ...
 */

В JavaDoc'у  отримую таку помилку:
**Cannot resolve symbol 'IntroducionTest'**
Як її позбутися?

**Comment by Stanislav-Zabramnyi** [comment]
@orelanc 
Так як посилання на **IntroducionTest** працює з цього класу, можу припустити, що це може бути якийсь баг IDE, на дошці jetBrains є декілька заведених тікетів з цього приводу, тому можливо скоро пофікситься.

якщо алерт сильно дратує, його можна вимкнути зайшовши в Preferences-> Editor-> Inspections-> Declaration has problems in Javadoc references і вимкнути опцію Report inaccessible symbols у вкладці Options.

**Comment by orelanc** [comment]
Спасибі за відповідь)!

ср, 3 серп. 2022, 15:14 користувач Stanislav-Zabramnyi <
***@***.***> пише:
